In [98]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.12.1+cu113
True


In [99]:
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [100]:
data = [[1,2],[3,4]]
x = torch.tensor(data)
x

tensor([[1, 2],
        [3, 4]])

In [101]:
np_array = np.array(data)
x = torch.from_numpy(np_array)
x


tensor([[1, 2],
        [3, 4]])

In [102]:
x.numpy()


array([[1, 2],
       [3, 4]])

In [103]:
x_ones = torch.ones_like(x)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0531, 0.0852],
        [0.6950, 0.7693]]) 



In [104]:
shape = (3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4486, 0.7206, 0.4899, 0.2355],
        [0.3755, 0.5891, 0.2930, 0.3840],
        [0.7178, 0.4011, 0.1356, 0.1906]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [105]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [106]:
device = torch.device("cuda")
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [107]:
tensor = torch.ones(3,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [108]:
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [109]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [110]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [111]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3,requires_grad=True)
print(x)
print(y)
print(w)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor([[-0.3163,  1.9425, -1.4376],
        [-1.4307,  1.5653, -1.0755],
        [ 2.3508,  0.2370,  1.8003],
        [-0.2655, -1.6298,  1.6074],
        [-0.2075,  0.6981, -0.6573]], requires_grad=True)
tensor([ 0.1369, -0.0572, -0.7120], requires_grad=True)


In [112]:
z = torch.matmul(x,w) + b
z

tensor([ 0.2677,  2.7559, -0.4748], grad_fn=<AddBackward0>)

In [113]:
loss_fn = torch.nn.BCEWithLogitsLoss()
loss = loss_fn(z,y)
loss

tensor(1.3791, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [114]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
loss

tensor(1.3791, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [115]:
loss.backward()
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor([[0.1888, 0.3134, 0.1278],
        [0.1888, 0.3134, 0.1278],
        [0.1888, 0.3134, 0.1278],
        [0.1888, 0.3134, 0.1278],
        [0.1888, 0.3134, 0.1278]])
tensor([0.1888, 0.3134, 0.1278])


In [116]:
z = torch.matmul(x,w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x,w) + b
print(z.requires_grad)

True
False


<https://tutorials.pytorch.kr/index.html>